import React from 'react'
import Head from 'next/head'
import Header from '../Header/Header'
import Footer from '../Footer/Footer'
const Layout = ({titlePage, children}) => {
  return (
    <>
      <Head>
            <title> {titlePage ? titlePage + " - Fest Record":"Fest Record"}  </title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main> {children} </main>
      <Footer />
    </>
  )
}

export default Layout
